server:
  #Spring Boot Applicaiton Port
  port: 8081

aws:
  dynamodb:
    #Endpoint that application might connect to
    endpoint: https://dynamodb.ap-northeast-2.amazonaws.com
  # Access credentials for the aws programmatic access. Please make sure that you donot share this information with others or commit
  # it to public.
  access:
    key: AKIA6OUKZSCOUWXGXXB6
    secret-key: ffzxLib/Zi4IstZLmYkhZvQxYt1Q6GGWBzp/6/2i
  # your AWS region where dynamo db instance is located.
  region: ap-northeast-2