package com.graphtype.application.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "article")

public class Article {

    @DynamoDBHashKey(attributeName = "articleId")
    @DynamoDBAutoGeneratedKey
    private String articleId;

    @DynamoDBRangeKey(attributeName="articleType") // sort key
    @DynamoDBAttribute
    private String articleType;

    @DynamoDBAttribute private String author;
    @DynamoDBAttribute private String createdAt;
    @DynamoDBAttribute private String updatedAt;
    @DynamoDBAttribute private boolean hidden;
    @DynamoDBAttribute private String title;
    @DynamoDBAttribute private List<String> contents;


}
